(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],S=window.SITE;if(!S)return;
const wa=k=>`https://wa.me/${S.whatsapp}?text=${encodeURIComponent(S.waMessages[k]||S.waMessages.general)}`;
const safe=(a,u)=>{try{const x=new URL(u);if(!['https:','tel:'].includes(x.protocol))return;if(x.protocol==='https:'){a.href=x.href;a.target='_blank';a.rel='noopener noreferrer'}else a.href=x.href}catch{}};
$$('[data-wa]').forEach(a=>safe(a,wa(a.dataset.wa)));$$('[data-map]').forEach(a=>safe(a,S.mapsUrl));$$('[data-ig]').forEach(a=>safe(a,S.instagram));$$('[data-tel]').forEach(a=>safe(a,'tel:'+S.phone));
$$('[data-menu]').forEach(a=>{if(S.menu.url)safe(a,S.menu.url);else{safe(a,wa('carta'));a.textContent=a.dataset.alt||'Consultar carta'}});
const st=$('#open-state');
if(st&&S.schedule){const tm=t=>{const[a,b]=t.split(':');return a*60+ +b};const upd=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).map(x=>[x.type,x.value]));const k=p.weekday.slice(0,3).toLowerCase(),m=(+p.hour)*60+ +p.minute;const open=(S.schedule[k]||[]).some(([a,b])=>m>=tm(a)&&m<(b==='24:00'?1440:tm(b)));st.textContent=open?'Abierto ahora · horario público':'Cerrado ahora · horario público';st.className='open-chip '+(open?'on':'off');st.hidden=false};upd();document.addEventListener('visibilitychange',upd)}
const g=$('#gallery');if(g){g.tabIndex=0;g.setAttribute('role','group');g.setAttribute('aria-label','Galería de fotos, desplazable')}
const header=$('#site-header'),onScroll=()=>header.classList.toggle('scrolled',scrollY>30);onScroll();addEventListener('scroll',onScroll,{passive:true});
const burger=$('#burger'),nav=$('#nav');const close=f=>{nav.classList.remove('open');burger.setAttribute('aria-expanded','false');burger.setAttribute('aria-label','Abrir menú');if(f)burger.focus()};
burger?.addEventListener('click',()=>{const o=!nav.classList.contains('open');nav.classList.toggle('open',o);burger.setAttribute('aria-expanded',String(o));burger.setAttribute('aria-label',o?'Cerrar menú':'Abrir menú')});
nav?.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('click',e=>{if(nav?.classList.contains('open')&&!e.target.closest('#site-header'))close()});addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open'))close(true)});
const motion=$('#motion');if(motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches){motion.hidden=false;motion.addEventListener('click',()=>{const c=document.documentElement.classList.toggle('calm');motion.textContent=c?'Reanudar movimiento':'Pausar movimiento';motion.setAttribute('aria-pressed',String(c))})}})();
