(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],S=window.SITE;const wa=k=>`https://wa.me/${S.whatsapp}?text=${encodeURIComponent(S.waMessages[k]||S.waMessages.general)}`;const setUrl=(a,u)=>{try{const x=new URL(u);if(x.protocol==='tel:'){a.href=x.href;return}if(x.protocol!=='https:')return;a.href=x.href;a.target='_blank';a.rel='noopener noreferrer'}catch{}};$$('[data-wa]').forEach(a=>setUrl(a,wa(a.dataset.wa)));$$('[data-map]').forEach(a=>setUrl(a,S.mapsUrl));$$('[data-ig]').forEach(a=>setUrl(a,S.instagram));$$('[data-tel]').forEach(a=>setUrl(a,'tel:'+S.phone));$$('[data-menu]').forEach(a=>{if(S.menu.url){setUrl(a,S.menu.url);a.textContent=a.dataset.label||'Ver la carta'}else{setUrl(a,wa('carta'));a.textContent=a.dataset.alt||'Consultar la carta por WhatsApp'}});const header=$('#site-header');const onScroll=()=>header.classList.toggle('scrolled',scrollY>40);onScroll();addEventListener('scroll',onScroll,{passive:true});const burger=$('#burger'),nav=$('#nav');const close=focus=>{nav?.classList.remove('open');burger?.setAttribute('aria-expanded','false');burger?.setAttribute('aria-label','Abrir menú');if(focus)burger?.focus()};burger?.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);burger.setAttribute('aria-expanded',String(open));burger.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});nav?.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('click',e=>{if(nav?.classList.contains('open')&&!e.target.closest('#site-header'))close()});addEventListener('keydown',e=>{if(e.key==='Escape'&&nav?.classList.contains('open'))close(true)});const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});$$('.opening-copy,.opening-note,.mesa-head,.dish,.dish-copy,.interlude,.pena-panel,.archivo-head,#gallery figure,.visit-intro,.visit-card,.contact-copy,.contact-mark').forEach(e=>{e.classList.add('rv');io.observe(e)})}const motion=$('#motion');if(motion&&!reduced){motion.hidden=false;motion.addEventListener('click',()=>{const calm=document.documentElement.classList.toggle('calm');motion.textContent=calm?'Reanudar movimiento':'Pausar movimiento';motion.setAttribute('aria-pressed',String(calm))})}})();

(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const hdr=$('#site-header'),bar=$('.progress'),img=$('.hero-img'),hero=$('.hero');const rm=matchMedia('(prefers-reduced-motion: reduce)').matches;let tk=0;const coarse=matchMedia('(pointer:coarse)').matches;
const upd=()=>{tk=0;const y=scrollY,m=document.documentElement.scrollHeight-innerHeight;bar&&bar.style.setProperty('--p',m>0?(y/m).toFixed(4):0);if(!rm&&img&&y<innerHeight*1.2&&!coarse)img.style.transform='translate3d(0,'+(y*.16).toFixed(1)+'px,0) scale(1.06)'};
addEventListener('scroll',()=>{if(!tk)tk=requestAnimationFrame(upd)},{passive:true});upd();
/* Estado abierto/cerrado (hora de Argentina) */
const H=[[[11,15],[20,24]],[[11,15],[20,24]],[[11,15],[20,24]],[[11,15],[20,24]],[[11,15],[20,24]],[[11,28]],[[0,4],[11,15]]];/* lun..dom; sáb hasta 04:00 del domingo */
const fmt=h=>String(h%24).padStart(2,'0')+':00';
const status=()=>{try{const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/Argentina/Buenos_Aires',weekday:'short',hour:'numeric',minute:'numeric',hour12:false}).formatToParts(new Date()),g=t=>p.find(x=>x.type===t).value,d=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(g('weekday')),t=(+g('hour')%24)+ +g('minute')/60;
const cur=(H[d]||[]).find(([a,b])=>t>=a&&t<b);let txt,cl=false;
if(cur){txt='Abierto ahora · hasta '+fmt(cur[1])}else{cl=true;let n=null;for(let i=0;i<7&&!n;i++){const dd=(d+i)%7;n=(H[dd]||[]).filter(([a])=>i>0||a>t).map(([a])=>[i,a])[0]}txt='Cerrado · abre '+(n?(n[0]===0?'hoy':n[0]===1?'mañana':['lunes','martes','miércoles','jueves','viernes','sábado','domingo'][(d+n[0])%7])+' '+fmt(n[1]):'pronto')}
$$('[data-status]').forEach(e=>{e.textContent=txt;e.classList.toggle('closed',cl)})}catch{}};status();
/* Lightbox */
const figs=$$('#gallery figure');if(figs.length&&'HTMLDialogElement'in window){const dl=document.createElement('dialog');dl.className='lb';dl.setAttribute('aria-label','Galería');const mk=(t,c,x,l)=>{const e=document.createElement(t);if(c)e.className=c;if(x)e.textContent=x;if(l)e.setAttribute('aria-label',l);return e};const wrap=mk('div','lb-in');wrap.append(document.createElement('img'),mk('p'),mk('button','x','✕','Cerrar'),mk('button','p','←','Anterior'),mk('button','n','→','Siguiente'));wrap.firstChild.alt='';dl.append(wrap);document.body.append(dl);let i=0;
const show=k=>{i=(k+figs.length)%figs.length;const im=$('img',figs[i]),l=$('img',dl);l.src=im.currentSrc||im.src;l.alt=im.alt;l.style.animation='none';l.offsetWidth;l.style.animation='';$('p',dl).textContent=im.alt};
figs.forEach((f,k)=>{f.tabIndex=0;f.setAttribute('role','button');f.addEventListener('click',()=>{show(k);dl.showModal()});f.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show(k);dl.showModal()}})});
dl.addEventListener('click',e=>{if(e.target===dl||e.target.classList.contains('lb-in')||e.target.closest('.x'))dl.close();else if(e.target.closest('.p'))show(i-1);else if(e.target.closest('.n'))show(i+1)});
dl.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(i-1);if(e.key==='ArrowRight')show(i+1)})}
})();
